### ISSUE TITLE
Añadir filtros por tipo y zona de la AAPP -maybe segunda fase.

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quiencobralaobra#100]
Para enviar a Karma las entidades catalanas, he creado este fichero que las separa por CCAA -a las que le aplica, no a ministerios o así. He pensado que, cuando nos pongamos de nuevo, tiene sentido añadir en los filtros la posibilidad de ver los contratos solo de una zona, por ejemplo. Hablándolo con Raúl, quizás tendría sentido que el filtro fuera una combinación de tipo y zona. Si nos ponemos, lo discutimos entre todos.

[Entidades por zona.xlsx](https://github.com/civio/quiencobralaobra/files/597293/Entidades.por.zona.xlsx)

**Comment by rauldiazpoblete** [comment]
Por concretarlo: lo que podría tener sentido es añadir un selector _Tipo de administración_ que tuviese las opciones _Ministerios / Comunidades Autónomas / Administraciones locales / Administraciones Andaluzas / Administraciones Aragonesas / Administraciones Catalanas / etc_

**Comment by EvaBelmonte** [comment]
Sí, lo que pasa es que aún no tengo 100% clara la división por categorías.
