### ISSUE TITLE
Implementar buscador

### ISSUE THREAD

**Issue by dcabo** [civio/quiencobralaobra#20]
Idealmente el buscador tendría que buscar en:

* [x] Nombre de administración pública, `public_body.name`
* [x] Objeto del contrato, `award.description` (de memoria)
* [x] Nombre de la empresa o del grupo, `bidder.name` y `bidder.group`
* [x] Contenido de los artículos

**Comment by EvaBelmonte** [comment]
@esebastian lo ha implementado para que busque en los contratos y devuelva la página de contratos filtrada por los criterios de búsqueda. La diferencia de este buscador con los criterios de filtrado de la página de contratos sería que este sí permite buscar en el objeto del contrato. Con eso podemos salir bien y lo tendríamos solucionado para el lanzamiento sin tener que hacer nada más, así que apuesto por dejarlo así por ahora y más adelante, con calma, vemos si queremos mejorarlo. @rauldiazpoblete ¿tú lo ves bien así por ahora? Así no tendrías que hacer página de resultados por ahora.

Solo como recordatorio: lo que se planteó en un inicio era que devolviera una página de resultados dividida en dos apartados: lo que viene de los contratos y lo que viene de los artículos. De todas formas, eso podemos ir discutiéndolo más adelante con calma.

**Comment by esebastian** [comment]
También permite buscar por nombre de la empresa, lo que no sé es si resultará confuso porque en los resultados mostramos el grupo constructor pero no el nombre de la empresa.

**Comment by EvaBelmonte** [comment]
Es un poco lío, sí. De hecho, como en la lista de contratos no aparece el objeto, no queda claro que haya filtrado por eso. La mejor opción sería la página de resultados planteada de forma inicial. Mi duda es si da tiempo a mejorarlo o salimos así. Me decís

**Comment by EvaBelmonte** [comment]
Visto que no salimos aún, vamos a por la opción fetén ;) ¡Gracias!

**Comment by esebastian** [comment]
Al final hemos optado por sacar los resultados en una página específica. He subido la estructura básica en c1ca40e y Raúl se encarga de darle forma.

**Comment by rauldiazpoblete** [comment]
La query actualmente está devolviendo resultados tanto de un grupo como de UTEs y empresas de ese grupo.
@esebastian , deberíamos eliminar tanto las UTEs como las empresas de un grupo de la búsqueda y devolver sólo grupos.

**Comment by esebastian** [comment]
He subido en b4c15ee la modificación que me pedía @rauldiazpoblete, y no sé si tendría sentido también modificar la búsqueda de contratos para que sólo lo haga por grupos, ya que ahora buscamos los contratos por varios campos (nombre de administración pública adjudicadora, objeto del contrato, nombre de la empresa, nombre del grupo) y nos pueden salir contratos que parecen fuera de lugar en el listado.

Un ejemplo de esto, a mi parecer, se daría con la búsqueda de 'ACS'.

**Comment by esebastian** [comment]
En el listado de resultados deberíamos tener en cuenta también el tema del particionado de las UTEs (#58).

**Comment by rauldiazpoblete** [comment]
Actualmente estamos buscando en los contratos por nombre de administración pública adjudicadora, objeto del contrato, nombre de la empresa y nombre del grupo y según @EvaBelmonte esto es suficiente. Así que podemos cerrar este issue.
