### ISSUE TITLE
¿Combinar Departamento y Organismo para el nombre de la entidad?

### ISSUE THREAD

**Issue by dcabo** [civio/quiencobralaobra#23]
Ahora estamos usando sólo el campo Organismo, que tiene valores como 'Junta de Contratación del Ejército de Tierra' para un [contrato de ejemplo](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-18063). Parece tener más sentido usar Departamento, que dice 'Ministerio de Defensa'.

Pero no podemos quedarnos sólo con el Departamento, porque a veces dice solo 'Administración Local' o 'Universidades'. En esos casos sí parece mejor usar el Organismo.

O tal vez debiéramos permitir los dos niveles de análisis, y mostrar el hecho de que la DGT o la Guardia Civil pertenecen al Ministerio del Interior (junto a varias Secretarías desconocidas).

**Comment by EvaBelmonte** [comment]
Si es posible que juntemos los dos, mejor. Pero combinarlos ahora mismo va a ser un trabajo complicado.

**Comment by dcabo** [comment]
Finalmente esto se limpió durante el proceso de consolidación de los distintos años, de forma semi-automática, vía el Excel `entities [manually cleaned].xlsx`. Así que el problema descrito (¡hace un año!) ya no aplica, ya estamos diciendo cosas como "Ministerio de Fomento", y podemos cerrar este issue.
