### ISSUE TITLE
Añadir herramientas de filtrado en la home de contratos

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#28]
Filtrar por:
- Empresa
- Administración
- Fecha de adjudicación (rango)
- Procedimiento

**Comment by rauldiazpoblete** [comment]
Añadir importe como otro elemento de filtrado

**Comment by rauldiazpoblete** [comment]
He modificado el selector de tipo de procedimiento en https://github.com/civio/quiencobralaobra/commit/70ad7fb32d1069c978453cd1fc3814b9e388dc84 a petición de @EvaBelmonte para usar sólo 3 valores de filtrado: `Abierto`, `Negociado` y `Otros`

**Comment by dcabo** [comment]
He implementado el filtrado por grupo y organismo público. Me faltan los otros criterios pero así sirve para desbloquear un poco el asunto.

Cosillas a cambiar en el front:

* [ ] El selector en realidad debería llamarse 'Grupo', no 'Empresa', porque eso es por lo que filtramos.
* [ ] Hay que añadir una opción vacía en los desplegables, seleccionada por defecto. Raúl, ¿esto es más fácil de hacer en el front o en el array que pasa el back? Sospecho que lo primero.
* [ ] Al cargar la página con los resultados el formulario no refleja el estado de la búsqueda: es decir, volvemos al estado por defecto.
* [ ] Raúl, ¿tienes previsto usar algún componente tipo Select2 para los desplegables?

**Comment by rauldiazpoblete** [comment]
En https://github.com/civio/quiencobralaobra/commit/5496613f7a8ce187f4f32ea5e9a02e4d25252903 he modificado `Empresa` para llamarlo `Grupo constructor` y añadido una opción inicial en los select para que por defecto aparezca `Todas las administraciones` y similar.

**Comment by rauldiazpoblete** [comment]
He añadido Select2 para los selectores de _Grupo_ y _Administraciones_ en https://github.com/civio/quiencobralaobra/commit/316a07ef9a8c6f30b58f300ac90f7d381289e655

**Comment by esebastian** [comment]
El filtro por tipo de contrato, fecha e importe está implementado en 63200bc.

**Comment by rauldiazpoblete** [comment]
Queremos modificar el slider de importe para que vaya por tramos. Según @EvaBelmonte usaremos: 
* 100.000
* 200.000
* 500.000
* 1 millón
* 5,225 millones
* 12 millones
* 100 millones

**Comment by esebastian** [comment]
En 87c9079 ya tenemos el formulario de filtro reflejando el estado de la búsqueda, sólo queda pendiente ajustar el valor del slider, de lo que se encargará @rauldiazpoblete a partir del valor que ahora se le asigna ahora al campo del formulario.

Queda pendiente también volver a agrupar los tipos de contrato en `Abierto`, `Negociado` y `Otros`, que no me he dado cuenta y lo he deshecho.

**Comment by esebastian** [comment]
A petición de @rauldiazpoblete, en e684490 he desactivado el paginado de los resultados cuando tengamos condiciones de filtrado, con el objetivo de poder usar la funcionalidad de ordenar en las columnas de las tablas.

**Comment by rauldiazpoblete** [comment]
Este issue está completo, pero antes de cerrarlo quiero comentar una cosa para tener en cuenta.
Estamos listando todos los contratos si hay algún criterio de búsqueda., lo que implica que si el único criterio de filtrado es por cantidad > 100.000 € nos devuelve unos 3500 contratos. @dcabo esto lo ves bien así o crees que puede suponer un problema de rendimiento?

**Comment by dcabo** [comment]
El listado se pagina? Si se pagina me parece ok.

**Comment by esebastian** [comment]
@dcabo ahora cuando se filtra no se pagina

**Comment by dcabo** [comment]
He probado a buscar los contratos >100.000€ y se me ha quedado el navegador tonto. Podemos limitar los resultados a, no sé, los 100 o 200 más grandes, y poner una nota debajo de la tabla que diga "sólo se muestran los primeros X resultados".

**Comment by rauldiazpoblete** [comment]
Hemos decidido limitar a 1000 resultados de búsqueda máximo mostrando un mensaje de aviso encima de la tabla en https://github.com/civio/quiencobralaobra/commit/c9f9a919a86f7b5cfc6bae9d1f72b7e3238bc279

**Comment by esebastian** [comment]
En b7a5052 he vuelto a agrupar el selector de tipo de procedimiento para usar sólo 3 valores de filtrado: 'Abierto', 'Negociado' y 'Otros'.
