### ISSUE TITLE
Incluir correcciones y mixtos -2015-

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quiencobralaobra#34]
Los mixtos que hay que incluir:

BOE-B-2015-2207
BOE-B-2015-5573
BOE-B-2015-11532
BOE-B-2015-11535
BOE-B-2015-11536
BOE-B-2015-11537
BOE-B-2015-32491

Las correcciones (son dos contratos, pero con varios campos cada uno. Hay que mirar si algún campo modificado se repite en más de una columna):

BOE ID,campo,correcci—n
BOE-B-2015-25557,Adjudicaci—n - Contratista,"ARIAS INFRAESTRUCTURAS, S.A."
BOE-B-2015-25557,Formalizaci—n del contrato - Contratista,"ARIAS INFRAESTRUCTURAS, S.A."
BOE-B-2015-36548,Formalizaci—n del contrato - Fecha de adjudicaci—n,22 de octubre de 2015
BOE-B-2015-36548,Formalizaci—n del contrato - Fecha de formalizaci—n del contrato,17 de noviembre de 2015
BOE-B-2015-36548,Formalizaci—n del contrato - Contratista,"Urcotex Inmobiliaria, S.L."
BOE-B-2015-36548,Formalizaci—n del contrato - Importe o canon de adjudicaci—n,"Importe neto: 566.869,28, Importe total: 685.911,83"

**Comment by dcabo** [comment]
Esto es la copia original (en el lugar incorrecto) del issue civio/boe#9, que ya se arregló en su día, así que lo cierro sin más.
