### ISSUE TITLE
Ordenar listados de administraciones y empresa por importe adjudicado total

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#36]

**Comment by dcabo** [comment]
Este issue es de hace 10 meses y sospecho que nuestra visión de la web ha cambiado: ¿seguimos queriendo ordenar por importe, o estamos contentos con nuestra solución actual?

**Comment by rauldiazpoblete** [comment]
Creo que es innecesario, dado que ya tenemos los gráficos de las 10 primeras entidades por importe, así que podemos cerrarlo.
