### ISSUE TITLE
Gráficos de contratación por grupo

### ISSUE THREAD

**Issue by dcabo** [civio/quiencobralaobra#41]
Eva: "Vamos a mostrar los datos globales por grupo, no por empresa. Hay que tener cuidado, a la hora de partir las UTEs, de no contar dos veces el mismo contrato cuando hay más de una empresa del mismo grupo."

**Comment by dcabo** [comment]
Acabo de ver este issue, entiendo que esto en realidad ya está, @rauldiazpoblete, creo que se ha quedado aquí olvidado...

**Comment by rauldiazpoblete** [comment]
Sí, yo no lo cerré por si lo tenías apontado por algo. Lo cierro entonces.
