### ISSUE TITLE
Probar gráficos de Datwrapper dentro de un artículo con custom styles

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#44]

**Comment by dcabo** [comment]
¿?

**Comment by EvaBelmonte** [comment]
Esto está planteado para ver si podemos meter datawrappers con estilos personalizados dentro de este proyecto y, si se puede, en el resto. Al principio la radiografía iba a llevar uno, pero finalmente lo descartamos. No es urgente
