### ISSUE TITLE
Definir las columnas que usaremos de la BBDD

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#45]

**Comment by rauldiazpoblete** [comment]
No vamos a usar todas las columnas de la base de datos, por lo que @EvaBelmonte tiene que pasarnos el listado de columnas que visualizaremos en la tabla de contratos

**Comment by EvaBelmonte** [comment]
@dcabo tiene que ver cómo encajar los datos, pero para que podamos ir viendo cómo montar las tablas de datos en la web y el gráfico principal, algunas cosas importantes:

* **Dos tablas**. He estado dándole muchas vueltas y creo que no es 100% riguroso sumar lo que se llevan en solitario y lo que se llevan en UTE a lo bruto y es una pena no dar ese valor, porque es muy importante. Así, si es posible, planteo dos tablas, que se pueda seleccionar una u otra. 

 * Opción A: 1) Lo que se llevan en solitario; 2) UTEs en las que participan. En la 1 sería todo lo que sea en solitario + UTEs en las que todas las empresas sean del mismo grupo. En la 2, UTEs en las que participan (excepto cosas en solitario y UTEs en las que todas las empresas sean del mismo grupo). 

 * Opción B: 1) Lo que se llevan en solitario; 2) Contratos en los que participan (en solitario o en UTEs, todo junto). En este caso, la 2 serían todos sus contratos, incluidos los de UTEs y sin restar los solitarios. Esto es, sumando todo, en línea con el titular de portada. ¡Ojo! Si usamos esta opción, tenemos que marcar las que son UTEs de alguna manera, para que se distingan. 

La segunda opción me parece más informativa, pero menos rigurosa. Aunque seguramente me la esté pillando con papel de fumar y creo que la opción B, bien explicada, sería la ganadora. ¿Es posible? ¿Le veis sentido? Es un cacao explicar bien el tema de las UTEs sin tener los malditos porcentajes.

* **Visualización principal de las 10 mayores constructoras**. Para que tenga sentido con el titular, algo como "10 constructoras, presentes en seis de cada 10 euros adjudicados en el BOE desde 2009 en contratos de obra" (mejorará), tenemos que hacer la trampilla de sumar contratos en solitario y UTEs. Como acabo de comentar, no se pueden sumar tal cual sin explicarlo bien, así que propongo que las barras de cada constructora, en lugar de estar partidas por tipo de contrato, estén partidas por "en solitario" y "UTEs en las que participan". El titular y subtítulo ayudará a que se entienda que no estamos sumando a lo loco. 

## Columnas a coger (tenemos que ver si caben todas bien en las tablas). 

* [QCLO] Contratista - Grupo (que no se mostrará en las tablas de páginas de grupos, pero sí en las de AAPP). Y la llamamos **GRUPO** o, si es posible, GRUPO CONSTRUCTOR. 
* [QCLO] Entidad adjudicadora - Nombre (que no se mostrará en las tablas de páginas de AAPP, pero sí en las de grupos). Y la llamamos **AAPP ADJUDICADORA**
* [QCLO] Contratista - Limpio - Y la llamamos **EMPRESA**. En la tabla con UTEs, aquí irá el nombre completo de la UTE, no la empresa, para que podamos dar esa info también. Pero eso dependerá de si decidimos coger la opción A o la B en las tablas.
* "Objeto del contrato - Descripción" Y "Objeto del contrato - Descripción del objeto". Estas dos columnas tienen que sumarse en una (issue #50). En algunos casos son textos larguísimos, así que tenemos que ver la manera de que no se muestren enteros por defecto y llenen todo de letricas. Y la llamamos **OBJETO**
* [QCLO] Fecha de adjudicación. Y la llamamos **FECHA DE ADJUDICACIÓN** o, si no cabe, **ADJUDICACIÓN**.
* [QCLO] Importe o canon de adjudicación - Limpio. Y la llamamos **IMPORTE**.
* "Tramitación y procedimiento - Procedimiento" Y "Análisis - Tramitación". Estas dos columnas tienen que sumarse en una (issue #50).Y la llamamos **TIPO**.
* URL PDF. Y la llamamos **FUENTE**.

Me estoy dejando algunas cosas que pueden ser relevantes, pero creo que ya va a ser bastante complicado meter todas estas columnas, que son las esenciales.

**Comment by EvaBelmonte** [comment]
Para la página de detalle de cada contrato:

* Descripción
* Tramitación
* Presupuesto base de licitación
* Fecha formalización
* Ámbito geográfico

**Comment by rauldiazpoblete** [comment]
Aunque aún hay campos por consolidar y algunas columnas que no se de dónde recoger sus datos, ya tenemos añadidas las columnas definidas en cada uno de los correspondientes layouts. También he añadido en https://github.com/civio/quiencobralaobra/commit/0f97481495eac9dc91bb1be788f9835c2662182c dos tablas diferentes para separar contratos con y sin UTEs.
Por tanto, y para simplificar, voy a cerrar este issue e ir abriendo otros issues para cada caso concreto que quede pendiente de corregir.

**Comment by dcabo** [comment]
Abro este issue para que el proceso de carga use las columnas correctas.

**Comment by dcabo** [comment]
@rauldiazpoblete, he extendido el modelo de datos para que un `Bidder` tenga el nombre de la empresa (como antes, en `name`) pero también el grupo (`group`) y el acrónimo (que posiblemente no haga falta de momento. De forma similar, ahora un `PublicBody` tiene un `body_type` en plan 'Ministerios' o 'Ayuntamientos'.

También he actualizado el fichero de datos de ejemplo en `data/awards.csv` para que tenga 100 contratos con el formato adecuado. Al cargar esos datos (`rake data:import_awards[db/awards.csv]`) se ven por ejemplo varias empresas, como Imesapi, que pertenecen al mismo grupo, ACS. Lo que no he hecho todavía es modificar las vistas existentes para mostrar el grupo donde ahora mostramos el nombre de empresa.

**Comment by dcabo** [comment]
@rauldiazpoblete, he creado también un campo `description` y otro `boe_id` en Award. De hecho he hecho un resumen del mapeo entre los campos que describió Eva en la primera lista con el modelo de datos, para que quede más claro. En vez de apuntar al PDF guardo simplemente el BOE ID, que puede ser más util en otras circunstancias (en listados, aunque sean internos, por ejemplo) y que permite generar enlaces al HTML, PDF o XML fácilmente.

**Comment by dcabo** [comment]
Cierro este issue y creo otros para cosas concretas, que serán mánejables.
