### ISSUE TITLE
Mejorar layouts de fichas de Empresas y Administraciones

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#48]

**Comment by rauldiazpoblete** [comment]
- [ ] Quitar las imágenes full-width
- [ ] Añadir frase automática bajo el título (tipo: _"Ferrovial se ha llevado X contratos por un importe de X €, de los cuales un X % ha sido por procedimiento negociado. La principal administración adjudicadora de Ferrovial ha sido X (X % del total del importe adjudicado)"_)
- [ ] Añadir gráfico de evolución temporal del importe de contratos adjudicados (será un stacked area chart y podremos seleccionar si se desglosa por Administración/Empresa adjudicadora/adjudicataria o por tipo de procedimiento, y en el caso de Grupos empresariales por empresas del grupo) -> Tanto en el gráfico como en las tablas de contratos **siempre deberemos usar la fecha de adjudicación**

**Comment by rauldiazpoblete** [comment]
¿@EvaBelmonte podrías confirmarme los _'textos robóticos'_?
De momento tengo:
- Para Grupos empresariales: _"Grupo X se ha llevado X contratos por un importe de X €, de los cuales un X % ha sido por procedimiento negociado. La principal administración adjudicadora de Grupo X ha sido X (X % del total del importe adjudicado)"_
- Para Administraciones: _"Administración X ha adjudicado X contratos por un importe de X €, de los cuales un X % ha sido por procedimiento negociado. El principal grupo empresarial beneficiado ha sido X (X % del total del importe adjudicado)"_

**Comment by EvaBelmonte** [comment]
* Para Grupos empresariales: "X se ha llevado de forma directa, entre 2009 y 2015, X contratos por un importe de X €. Además, ha formado parte de UTEs que resultaron adjudicatarias de otros X contratos y que suman otros X euros. Así, X ha estado presente, en total, en la adjudicación de X contratos y X euros. De esa cantidad, un X% del importe fue adjudicado vía procedimiento negociado. Entre las administraciones que le contratan, la que tiene mayor peso es X (X % del total del importe adjudicado tanto de forma directa como a través de las UTEs en las que participa)."

* Para Administraciones: "X ha adjudicado X contratos por un importe de X €, de los cuales un X % ha sido por procedimiento negociado. El principal grupo empresarial beneficiado ha sido X (está presente, de forma directa o a través de UTEs, en el X % del total del importe adjudicado)"

**Comment by rauldiazpoblete** [comment]
Las frases ya están actualizadas en https://github.com/civio/quiencobralaobra/commit/5b5ccbb3e6126554a1429082d56e8f67e6227616. Está pendiente integrar los datos en las frases pero lo muevo a su propio issue (#56)

**Comment by rauldiazpoblete** [comment]
Elimino el punto con el gráfico de evolución temporal y lo muevo a su propio issue.

**Comment by EvaBelmonte** [comment]
Para Grupos empresariales: "De todas las adjudicaciones publicadas en el BOE entre 2009 y 2015, X se ha llevado de forma directa X contratos por un importe de X €. Además, ha formado parte de UTEs que resultaron adjudicatarias de otros X contratos y que suman otros X euros. Así, X ha estado presente, en total, en la adjudicación de X contratos y X euros. De esa cantidad, un X% del importe fue adjudicado vía procedimiento negociado. Entre las administraciones que le contratan, la que tiene mayor peso es X (X % del total del importe adjudicado tanto de forma directa como a través de las UTEs en las que participa)."

Para Administraciones: "De todas las adjudicaciones publicadas en el BOE entre 2009 y 2015, X ha adjudicado X contratos por un importe de X €, de los cuales un X % ha sido por procedimiento negociado. El principal grupo empresarial beneficiado ha sido X (está presente, de forma directa o a través de UTEs, en el X % del total del importe adjudicado)"

**Comment by EvaBelmonte** [comment]
Lo abro un segundín porque he modificado un poco los textos.
