### ISSUE TITLE
Combinar las columnas de objeto y procedimiento al cargar los datos

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quiencobralaobra#50]
Hay que combinar en una sola columna (y asegurarnos de que no quedan blanks): 
- "Objeto del contrato - Descripción" Y "Objeto del contrato - Descripción del objeto" 
- "Tramitación y procedimiento - Procedimiento" Y "Análisis - procedimiento".
- "Tramitación y procedimiento - tramitación" Y "Análisis - tramiración".

Las resultantes serán las columnas que usemos en las tablas, así que urge un poquillo. Igual hay que limpiar un poco, pero de eso me puedo encargar yo si quieres, @dcabo

**Comment by dcabo** [comment]
Revisar el issue #45, donde se explican qué columnas vamos a usar.

**Comment by dcabo** [comment]
Esto engancha con civio/boe#44, que va de lo mismo.

**Comment by dcabo** [comment]
He preparado un Excel con los datos de Procedimiento y Tramitación de todos los contratos que estamos manejando (de obra, o sea, los que entran en la aplicación). He dejado las dos columnas de Análisis por un lado, y las que vienen del cuerpo del anuncio por otro. Y luego las he consolidado en dos columnas (coloreadas), dando preferencia a Análisis cuando existe. (También he dejado una columna medio rara que creo que no aporta nada, pero por si acaso.)

Así podemos evaluar -Refine está bien para contar estas cosas- cuántos contratos no tienen ningún tipo de información o la tienen de muy poca calidad. Hay unos ~450 (de 8340) que no tienen ningún dato sobre esto y que podemos agrupar en una categoría 'Desconocido' o similar.

[Procedimiento_y_Tramitacion.xlsx](https://github.com/civio/quiencobralaobra/files/554645/Procedimiento_y_Tramitacion.xlsx)

**Comment by dcabo** [comment]
Para procedimiento vamos a agrupar en: abierto, negociado con publicidad, negociado sin publicidad, negociado (a secas, cuando no especifica más), y 'sin información', cuando no sepamos capaces de adivinar de qué se trata. Buscaremos cadenas como 'abiert' o 'negociad'. Es un campo importante, así que miraremos también en otros campos para rescatar aquellos casos donde la información está en el lugar incorrecto o se menciona de pasada en otros campos.

Para tramitación usaremos: ordinario, emergencia, urgente y sin información.

**Comment by dcabo** [comment]
Como paso intermedio he añadido dos columnas, '[QCLO] Procedimiento' y '[QCLO] Tramitación', que consolidan los distintos valores que aparecen desperdigados en cada anuncio. Básicamente dan prioridad al campo de Análisis, cuando existe, y si no se quedan con lo que aparezca en uno de los dos campos posibles del cuerpo.

El siguiente paso es estandarizar estos valores en las categorías que hemos definido. Podríamos hacerlo todo del tirón, pero es útil tener este paso intermedio para poder luego verificar la limpieza automática que hagamos.

**Comment by dcabo** [comment]
He empezado limpiando 'Tramitación', que es más sencillo. He empezado aceptando todas las erratas que he encontrado, vía expresión regular, que es algo que habría que ajustar de cara a futuros años pero de momento va bien. Luego he revisado los registros que no tenían información, para ver si tenía sentido buscar cosas como "ordinario" o "urgente" en todo el cuerpo del anuncio: mi conclusión es que no, porque aparecen contratos de "conservación ordinaria de carreteras" o "hospital de urgencias". Lo que sí tiene sentido, viendo que es un error común, es buscar en el campo de 'Procedimiento' si el de 'Tramitación' no dice algo con sentido. Haciendo esto, y volviendo a revisar los contratos que se quedan sin información (508 en total), sólo hay uno que diga "ordinaria" en el cuerpo, el de carreteras. Lo que sí podemos hacer, en plan esfuerzo final, es mirar exclusivamente en el título, y buscar "Urgente", porque hay un bloque gordo de anuncios de Fomento. Haciendo esto acabamos con 484 registros sin información de Tramitación, de 8339, y no se me ocurre forma de rebajar ese número, porque no hay más información disponible.

Como resumen, y a modo de verificación, estos son todos los casos distintos entrada->salida que se dan en el proceso de limpieza (pero sin mostrar las columnas de título o de procedimiento, porque si las meto no puedo eliminar duplicados en Excel y tendría que mostrar los 8000 registros):

[Mapeo Tramitación.xlsx](https://github.com/civio/quiencobralaobra/files/565206/Mapeo.Tramitacion.xlsx)

@EvaBelmonte, podría poner 'Ordinaria' en aquellos casos en los que no dice otra cosa, como me digas. Aunque yo creo que es mejor dejarlos en blanco, porque eso te da a ti la flexibilidad, al hacer un cálculo determinado, de incluirlos o no, según veas mejor. Mientras que si les pongo 'Ordinaria' al juntar los datos tú luego no puedes saber si es algo real o una corazonada.

**Comment by dcabo** [comment]
Repetimos el mismo proceso con 'Procedimiento': usamos expresiones regulares para detectar las variantes comentadas más arriba, y miramos en el campo de 'Tramitación' si no encontramos nada, porque es un error común. Nos quedan 453 contratos sin información. Viendo que se repite una situación similar al de 'Tramitación', donde el título a veces contiene información útil, pasamos a utilizarlo como plan C. Y nos quedamos con 437 en blanco. En este punto, de los restantes, las únicas referencias en todo el anuncio a "negociado" son en tres casos aislados, en la firma, en plan "el jefe del negociado". "Publicidad", "diálogo" o "restringido" no aparecen, y sólo se dice "abierto" dos veces como parte del número de expediente. Creo que estamos sacando toda la información disponible.

El campo 'Análisis - Tipo' parece tener cierta relación con el procedimiento, porque 'Adjudicación Directa' correlaciona bastante con los negociados, pero hay casos donde [son abiertos](http://boe.es/buscar/doc.php?id=BOE-B-2010-19738), así que tampoco nos podemos fiar. Y al revés: el valor 'Adjudicación Concurso de Obras' parece apuntar a un procedimiento abierto, pero hay [bastantes casos](http://boe.es/buscar/doc.php?id=BOE-B-2010-9872) donde en realidad son negociados. Así que realmente no te puedes fiar del Tipo del análisis.

Dejo aquí de nuevo un resumen del mapeo entrada->salida:

[Mapeo Procedimiento.xlsx](https://github.com/civio/quiencobralaobra/files/565322/Mapeo.Procedimiento.xlsx)

@EvaBelmonte: mi única duda aquí es, de forma similar a la pregunta anterior, si quieres que distinga entre los casos que no dicen nada y aquellos que dicen algo absurdo tipo 'Armonizado'. Yo creo que diferenciar esto genera confusión y no le veo valor. Yo dejaría en ambos casos el campo vacío en el CSV/XLS maestro. Dejarlo vacío en el Excel no nos impide luego poner "Sin información" en los listados de la web, claro, a la vez que refleja mejor la realidad de los datos.

**Comment by EvaBelmonte** [comment]
* No entiendo bien algunas equivalencias de entrada y de salida en ambos Excel. Me centro en el de procedimiento, que es el más importante. Hay dos líneas con la casilla vacía en la columna de la izquierda, la de entrada. En una de ellas pone 'negociado sin publicidad' y en otra 'abierto'. ¿Esto por qué es? 

* Hay ciertas expresiones en la columna de entrada que yo traduciría como 'abierto' directamente: 'general', 'varios criterios' y seguramente 'A', aunque tendría que ver el caso/s concreto.

* De acuerdo en que prefiero saber de dónde viene cada campo y que estén vacíos aquellos en los que no hayamos sacado información (y no con 'abierto' u 'ordinario' por defecto, aunque yo pueda explicar en el  texto que esos seguramente sean 'abiertos' y 'ordinarios'. 

* Me sigue jodiendo que queden tantos sin información en el negociado, la verdad. Es uno de los puntos clave de la investigación, que prometimos, y no vamos a poder dar tampoco cifras reales. Si no fuera porque no tenemos tiempo ahora, deberíamos hacer una limpieza manual. De verdad, esto es muy importante. :'(

* En las tablas, tanto para procedimiento como negociado, cuando el campo esté vacío podemos poner una raya, @rauldiazpoblete Me da miedo poner "no info" o similar cuando no estamos 100% seguros de que no esté escondida en algún rincón extraño del anuncio.

**Comment by rauldiazpoblete** [comment]
He añadido un guión en aquellos `Procedimientos` y `Tramitaciones` vacías en https://github.com/civio/quiencobralaobra/commit/8dce1c575af594e2fc09dc9f666c5bd81ef9187e

**Comment by dcabo** [comment]
@EvaBelmonte: ¿están claras mis respuestas a tus comentarios? ¿algo más que hacer?

**Comment by EvaBelmonte** [comment]
Todo claro, gracias. Cierro
