### ISSUE TITLE
Preguntas básicas de las 10 mayores constructoras

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quiencobralaobra#52]
Imagino que es más sencillo preguntarle a la BBDD de forma directa, @dcabo. Necesitaría saber:
- ¿Con quién prefieren ir en UTE?

Cuando estén las columnas de ámbito geográfico y procedimiento (#50), de ahí sacaré % de negociados y concursos, zonas favoritas...

**Comment by dcabo** [comment]
Sobre quién va con quién, lo he calculado en Excel montando un pequeño tinglado, una matriz de 10x10 para ver en qué contratos (lotes, en realidad) está cada uno de los diez grupos. Al final el resumen es:

[Socios favoritos.xlsx](https://github.com/civio/quiencobralaobra/files/576501/Socios.favoritos.xlsx)
