### ISSUE TITLE
Añadir contenido sección 9 de 'La ley'

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#55]

**Comment by rauldiazpoblete** [comment]
También debemos revisar el contenido de las demás secciones dado que hay algunas anotaciones y contenido no definitivo

**Comment by EvaBelmonte** [comment]
##9.El espejismo de las bajas temerarias
Ofertas "anormalmente bajas", "desproporcionadas" o, más común, "bajas temerarias". Todas esas expresiones se refieren a lo mismo: el empresario asegura que va a ofrecer un servicio, un suministro o a levantar una obra pública a un precio o en unas condiciones que no parecen creíbles. Y eso significa que puede poner en peligro su ejecución. O, lo que es lo mismo, que prometa pero no cumpla y lo deje a medias, tenga que pedir una ampliación del presupuesto o la calidad del resultado sea nefasta o incluso peligrosa. Para evitar todos estos males, las leyes establecen límites a las bajas temerarias. 

Las directivas europeas dejan a los países la definición, en sus propias leyes, de estas ofertas desproporcionadas. Y aclaran que no se puede excluir de forma directa una oferta solo por serlo. Del mismo modo se refleja en el [reglamento de la Ley de Contratos del Sector Público](https://www.boe.es/buscar/act.php?id=BOE-A-2001-19995#a152): antes de rechazar una oferta "anormalmente baja" es obligatorio dar trámite a la empresa que la ha propuesto para que justifique sus bajos precios. Así, se pide un informe y, si convence a los responsables de la contratación, -algo que es habitual, como explican diversas fuentes del sector- se adjudica igualmente, aunque sea una baja temeraria. Esta es la razón por la que, en muchísimos casos, el límite legal a estas prácticas no es más que un espejismo. 

###¿Qué es una baja temeraria?
El [reglamento de la Ley de Contratos del Sector Público](https://www.boe.es/buscar/act.php?id=BOE-A-2001-19995#a85) distingue entre concursos (contratos con varios criterios de adjudicación) y subastas (contratos en los que el único criterio es el precio). Para los primeros, los pliegos "pueden" establecer baremos para determinar qué es una baja temararia, pero no están obligados. De hecho, si la fórmula para el cálculo no está en los pliegos, está prohibido aplicar ninguna y excluir a una empresa por esa razón. 

Caso bien distinto es el de las subastas, en el que las reglas básicas establecen que son bajas temerarias:

* Si hay un licitador, una rebaja de más del 25% con respecto al precio de licitación.
* Con dos licitadores, si una oferta es inferior a la otra en más de un 20%.
* Con tres licitadores, las ofertas que rebajen la media aritmética más de un 10%. Pero se excluirá del cálculo la oferta más elevada si supera en más de un 10% esa media. En todo caso, siempre será baja temeraria la baja superior a un 25%.
* Con cuatro o más licitadores, las ofertas que rebajen la media en más de un 10%. Como en la anterior, también se excluyen aquí las ofertas que superen en un 10% la media.

Esta es la base legal. Según cada caso concreto, el organismo contratador podrá reducir un tercio esos porcentajes en los pliegos. Eso sí, deberá motivar su decisión. 

###La otra cara de la moneda
Pero, si las bajas suponen una rebaja en el precio a pagar, ¿por qué se limitan? Aunque su sentido primario es evitar ampliaciones y ejecuciones deficientes, la CNMC alerta que, en ocasiones, el precio de licitación tiene poco que ver con el coste real y es normal que se produzcan esos desajustes. "La elaboración de esos presupuestos normalmente sigue procesos con deficiente transparencia y escasa relación con los precios efectivos de mercado", critica en su [informe sobre la contratación pública](https://www.cnmc.es/Portals/0/Notas%20de%20prensa/201502_Informe_ContratacionPublica.pdf). 

O, lo que es lo mismo: "La CNMC ha detectado a menudo que una baja significativa por parte de un operador respecto al presupuesto estimado de licitación no refleja necesariamente una ganancia de eficiencia respecto a los precios de mercado, y mucho menos una “baja temeraria”, sino una inadecuada aproximación por el órgano de contratación a los costes que ha estimado".
