### ISSUE TITLE
Integrar datos en las descripciones de AAPP y Empresas

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#56]

**Comment by rauldiazpoblete** [comment]
He integrado algunos de los datos en https://github.com/civio/quiencobralaobra/commit/a7a6e1b8e8733fb14f4ca77eb5244fe372570a00.
Entre ellos el número de contratos totales y el importe total (también con UTEs aunque de momento son sólo datos falsos).
Faltaría por añadir:

* en Grupos y AAPP
- [ ] % de contratos por procedimiento negociado

* en Grupos
- [ ] principal APP adjudicadora (en solitario + UTEs) y su % adjudicado del total del importe

* en AAPP
- [ ]  principal grupo empresarial beneficiado (en solitario + UTEs) y su % adjudicado del total del importe

**Comment by EvaBelmonte** [comment]
Solo por aclarar, el % de negociado debe sumar los tres tipos (sin, con, negociado a secas)

**Comment by dcabo** [comment]
@rauldiazpoblete, me dice Eva que querías comentarme algo sobre esto de las fichas robóticas. ¿Cómo te puedo ayudar?

**Comment by dcabo** [comment]
Esto ya debería estar para todos los casos, pero dejo que @EvaBelmonte lo revise.

**Comment by EvaBelmonte** [comment]
He revisado en diagonal en varios supuestos, y parece que todo encaja. Cierro. Si nos encontráramos algo estos días, aviso. ¡Gracias!
