### ISSUE TITLE
En el listado de contratos debemos de mostrar los nombres de las UTEs partidos por los grupos que los conforman

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#58]

**Comment by rauldiazpoblete** [comment]
Comentando con @EvaBelmonte hemos decidido que en el listado de la página de Contratos mantendremos la columna de 'Grupo constructor' tanto para los contratos de Grupos como para los de UTEs. En el caso de un contrato de una UTE deberíamos mostrar en la columna 'Grupo constructor' el texto _UTE: Grupo1 / Grupo2 / Grupo3_, donde el nombre de cada grupo linka a su ficha correspondiente

**Comment by dcabo** [comment]
El nombre de la UTE muchas veces no incluye los nombres de las empresas que lo forman, y en general no coinciden exactamente. Así que si queremos enlazar a las empresas tenemos que generar la lista nosotros mismos, a partir de las tablas de UTE->empresas que tenemos. No es difícil, porque esa información la vamos a tener en la aplicación en cualquier caso.

La pregunta, @EvaBelmonte, @rauldiazpoblete, es si queréis tener el nombre de la UTE **Y** el listado de empresas, o solo una de las dos cosas.

**Comment by dcabo** [comment]
Me comenta Eva que queremos tener la lista de empresas, no el nombre de la UTE, así que aclarado.

**Comment by EvaBelmonte** [comment]
Acabo de entender que esto no es solo una cuestión de cómo lo mostramos, sino que afecta a que haya páginas de UTE como si fueran grupos. Hasta ahora no veía la importancia, porque no entendía cómo estaba estructurada la base de datos en la web y que todo iba en el mismo saco. ¿Cómo de costoso es esto, @dcabo @esebastian? ¿Veis posible que entre para el lanzamiento? Si no es así, decidme y pensamos una alternativa, porque es importante y tal y como se muestra ahora es un pelín caos.

**Comment by dcabo** [comment]
Hasta ahora estábamos mostrando las UTEs como grupos en sí mismos, porque es una consecuencia natural de cómo estamos importando los datos. Pero esto es un jaleo para el usuario y "no luce" el trabajo que hemos hecho identificando y partiendo las UTEs. Así que, por concretar, vamos a, en orden de dificultad:

* [ ] No mostrar las UTEs en la lista de grupos constructores.
* [ ] No enlazar a la página de la UTE en la página de detalle de un contrato y en los listados (de administraciones y de contratos).
* [ ] Reemplazar en la página de detalle y en los listados el nombre de la UTE por un texto que diga "UTE: Grupo 1 / Grupo 2", con enlaces a las páginas correspondientes.

Yo puedo hacer esto en la tarde/noche argentina, para que esté antes del lanzamiento.

**Comment by esebastian** [comment]
En la pagina de resultados de búsqueda (`/app/views/pages/search.html.erb`) tenemos ahora también otro listado de contratos, que habrá que tener en cuenta.

**Comment by dcabo** [comment]
Por aclarar, que ha habido algunas dudas, y confirmado por Eva: cuando hablamos del listado de "grupos" y de que hay que quitar las UTEs, seguimos queriendo mostrar los grupos que están formados por una sola empresa. Es decir, si "Pinturas Manolo" es una empresa independiente, sin filiales ni nada, ella forma su propio grupo "Pinturas Manolo", y tiene que estar en el listado. Lo que no queremos es mostrar "UTE: Pinturas Manolo / Dragados", sino los grupos que la forman.

**Comment by esebastian** [comment]
He modificado la query en el controller de bidders para que no se muestren las UTEs en la lista de grupos constructores.

Está modificada también en el combo del buscador de contratos (#28) y en el listado de grupos del buscador general (#20).

**Comment by rauldiazpoblete** [comment]
A petición de @dcabo he creado en https://github.com/civio/quiencobralaobra/commit/9d88a686de02968f718ef1adb66f5bd2c3bbba4f un helper `render_bidder_group` para mostrar el nombre de un grupo constructor. No lo he podido añadir en los listados de contratos porque hay algún problema con las peticiones de las queries y bloquea la carga de la página. No obstante lo he dejado comentado en `views/partials/_contract_awards_table.html.erb` para activarlo cuando solucionemos este problema de carga.

**Comment by dcabo** [comment]
Cacheado el cálculo de los grupos de las UTEs, y activado el desglose por grupos en los listados. Con esto debería estar todo listo, si me he dejado algún lugar creamos otro issue.

**Comment by rauldiazpoblete** [comment]
Sólo para que quede constancia: dado que quedaban raro los casos en los que todas las empresas de la UTE pertenecen al mismo grupo y el nombre del grupo quedaba como `UTE: ACS`, comentándolo con @EvaBelmonte hemos decidido no mostrar el prefijo `UTE:` si no hay más de un grupo implicado.
Así que he modificado el helper `render_bidder_group` en https://github.com/civio/quiencobralaobra/commit/3ef1dc6eb62414cc342d29f430b8c2363b14aa4b para ello.
