### ISSUE TITLE
Revisar que cargamos correctamente los campos de detalle de los contratos

### ISSUE THREAD

**Issue by dcabo** [civio/quiencobralaobra#60]
A partir del listado de Eva en el #45, necesitamos:
- [x] Descripción => ya lo tenemos en `award.description`
- [x] Tipo => parte de #50 (hasta ahora estamos usando `award.category`)
- [x] Tramitación => parte de #50 
- [ ] Presupuesto base de licitación
- [ ] Fecha formalización
- [ ] Ámbito geográfico

**Comment by dcabo** [comment]
Me comenta Eva que no necesitamos tener estos campos limpios, así que simplemente los mostramos en la página de detalle a partir de `properties` y listo.

**Comment by rauldiazpoblete** [comment]
La Fecha de formalización la estamos cogiendo actualmente de `properties['Formalización del contrato - Fecha de formalización del contrato']` pero puede que se encuentre en otras propiedades, por lo que @dcabo tiene que consolidarlo tal y como ya ha hecho con `description`en https://github.com/civio/quiencobralaobra/commit/2206d7399c23d05d1d9acd62c1033f4b6bcee0ed

**Comment by dcabo** [comment]
Lo he comprobado, y no, la formalización sólo aparece en una posible columna, la que ya estamos usando. Es distinto al caso de la adjudicación, dónde puede venir por dos vías, 'Adjudicación - Fecha' y 'Formalización del contrato - Fecha de adjudicación'. Así pues estamos haciendo ya todo lo posible.

Los otros dos campos mencionados originalmente, 'Presupuesto base' y 'Ámbito geográfico', se muestran ahora en la página de detalle de un contrato, sin procesar, y no hay problemas de que vengan vía distintas columnas, así que listo.
