### ISSUE TITLE
Modificar listados para usar nombres de grupo

### ISSUE THREAD

**Issue by dcabo** [civio/quiencobralaobra#61]
Hasta ahora los listados mostraban los nombres de las empresas, pero gracias a #45 ahora tenemos el nombre del grupo, que es el que nos interesa más. Tenemos que revisar los distintos listados para usar el grupo.

Ya que estamos revisamos que usamos también los otros nuevos campos, como `award.description` o `award.boe_id` para enlazar al BOE (yo enlazaría al HTML, por cierto, que tiene cosas adicionales al PDF, como la sección de Análisis).

@rauldiazpoblete, ¿te lo asigno, que sabes mejor dónde están los templates de cada cosa? En general la idea es que en los listados no se tenga que acceder a `award.properties`, va a ser todo más sencillo y más rápido y más limpio si esos campos importantes están en el propio objeto, y no en una lista de propiedades con nombres raros.

**Comment by dcabo** [comment]
En realidad creo que ya está todo lo relacionado con nombre vs. grupo, y alguna cosilla más que he hecho para aprovechar los nuevos campos de datos, pero échale un ojo por si acaso a la web, Raúl, por si hay algo que me he dejado.

**Comment by rauldiazpoblete** [comment]
Lo he revisado y en principio veo todo ok, por lo que cierro el issue.
