### ISSUE TITLE
Definir el rango temporal de los datos

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#65]

**Comment by rauldiazpoblete** [comment]
En las descripciones de las fichas de AAPP y Empresas ponemos _XXX ha adjudicado, entre **2009 y 2015**, x contratos  ..._ pero en algunos casos tenemos contratos de 2008 (ACS por ejemplo tiene unos cuantos). Al pintar el gráfico de evolución yo estaba delimitando el eje x del gráfico entre 2009 y 2015, lo cual dejaría fuera algunos contratos en estos casos. ¿Tenemos alguna fecha fija a partir de la cual tenemos datos o es variable?

**Comment by EvaBelmonte** [comment]
El rango preciso es: adjudicaciones publicadas en el BOE entre 2009 y 2015. Sabemos que hay: 
* Datos de 2008: se adjudicaron a finales de año y se publicaron en el BOE de 2009.
* 1 contrato de 2005 y 2 contratos de 2007. 
( y hay que tener en cuenta que faltarán contratos de 2015, publicados en BOE de 2016, pero eso solo me afecta a mí para las notas al pie)

Solución: no mostramos esos tres contratos rarunos de 2005 y 2007 en los gráficos, porque desvirtuaría todo, pero sí arrancamos con 2008 el eje. 

Y tengo que mejorar, ahora que lo comentas, el redactado robótico.

**Comment by rauldiazpoblete** [comment]
Ok. Entonces arrancaré por defecto los gráficos en 2009 y en caso de que haya contratos de 2008 amplio el gráfico.

**Comment by rauldiazpoblete** [comment]
Dado que ya se han actualizado las descripciones de las entidades en https://github.com/civio/quiencobralaobra/commit/e13bc3ff28abb55f5e632eebb61af6a911e2316d y he corregido el arranque del eje-x del gráfico temporal en https://github.com/civio/quiencobralaobra/commit/03f6a9eb1fb57c50a8363fecead9c648a92b2d8b puedo cerrar este issue
