### ISSUE TITLE
Desplegar la web en producción

### ISSUE THREAD

**Issue by dcabo** [civio/quiencobralaobra#71]

**Comment by esebastian** [comment]
Si puedo echar una mano, avisadme.

**Comment by dcabo** [comment]
Que hoy es festivo! :D Mañana lo hablamos ;)

**Comment by dcabo** [comment]
La web está funcionando correctamente en mola.quiencobralaobra.es, en un nuevo servidor. La URL final será sin el 'mola'.

Sólo faltaría montar el Let's Encrypt para el HTTPS, y Eduardo quería tocar alguna cosa interna más.

**Comment by dcabo** [comment]
He protegido la web con contraseña, para hacer el prelanzamiento a donantes, usando [estas instrucciones bastante claras](https://www.digitalocean.com/community/tutorials/how-to-set-up-http-authentication-with-nginx-on-ubuntu-12-10). El usuario es 'quiencobra', la contraseña es 'laobra'.

También he cambiado el DNS de `quiencobralaobra.es` y `www.quiencobralaobra.es` para que apunten a la nueva web (`mola.quiencobralaobra.es` sigue funcionando, pero ya no tiene sentido usarlo). Cuando os levanteis el cambio debería estar ya propagado. Eduardo, pensaba que el DNS de esta web estaba en Namecheap, pero resulta que está en Linode, perdona la confusión.

Lo que no he hecho es redirigir de la versión con `www.` a la versión "sin", que es la favorita, pero eso es algo que podemos hacer después de lanzar cuando tengamos un momento de respiro.

**Comment by esebastian** [comment]
Ya está activado el `HTTPS` en el servidor, con la redirección automática de las peticiones `HTTP` a `HTTPS`.

También he activado la redirección de la versión `www.` a la version sin.

**Comment by dcabo** [comment]
La web ya está desplegada y funcionando, así que voy a cerrar este issue y creamos otros nuevos para cosas concretas que vayan saliendo.
