### ISSUE TITLE
Banderas rojas

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quiencobralaobra#73]
Después del trabajazo que ha supuesto sacar los datos de esta primera fase, he pensado que tiene sentido sacar banderas rojas de un año. Por ejemplo, 2015. Y ver qué tal, si tiene chicha por sí mismo. Una cosa que tiene sentido es, si metemos los datos de 2016 para actualizar, hacer banderas rojas sobre ellos para darle una segunda bola al proyecto el año que viene. Lo vemos, es solo para que no se me olvide.

**Comment by dcabo** [comment]
Relacionado con civio/boe#45
