### ISSUE TITLE
Incluir cositas de developers en la metodología

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quiencobralaobra#74]
Ya hay primera versión. Está en artículos/metodología/metodología.md

@dcabo Miguel lo va a revisar, pero léelo tú también y añade lo que consideres.

@dcabo @rauldiazpoblete Hay un punto 10 sobre la web. Be my guests

**Comment by EvaBelmonte** [comment]
Otra cosa: ¿vamos a poner enlace a Github? ¿Dónde os parece? En todo caso, no quiero que se publiquen los datos de forma descargable, ni siquiera una versión sucia, hasta que hagamos banderas rojas. ¿Podéis poner un csv de muestra con una decena de contratos y quitar lo que hay ahora, por ejemplo? Explico las razones en el documento de metodología, por si necesitáis justificarlo por aquí.

**Comment by rauldiazpoblete** [comment]
Yo he añadido un par de líneas básicas con el stack tecnológico que usamos y enlace al repositorio en Github. Quizás es necesario especificar también la licencia de uso del código (que por cierto tenemos que incluir en el repositorio como apunté en #49)

**Comment by rauldiazpoblete** [comment]
Como ya tenemos la licencia en el propio repo y esta enlazado podemos obviar la licencia en la metodología. Cierro el issue.
