### ISSUE TITLE
Caras constructores con casco

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quiencobralaobra#76]
* ACS. Florentino Pérez > http://quienmanda.es/people/florentino-perez-rodriguez
* Acciona. José Manuel Entrecanales > http://quienmanda.es/people/jose-manuel-entrecanales
* Isolux Corsán. Luis Delso > http://quienmanda.es/people/luis-delso-heras
* Ferrovial. Rafael del Pino > http://quienmanda.es/people/rafael-del-pino-calvo-sotelo
* FCC. Esther Alcocer Koplowitz > http://quienmanda.es/people/esther-alcocer-koplowitz
* Sacyr. Manuel Manrique > http://quienmanda.es/people/manuel-manrique-cecilia
* Grupo Villar Mir. Juan Miguel Villar Mir > http://quienmanda.es/people/juan-miguel-villar-mir
* Comsa. Jorge Miarnau > http://quienmanda.es/people/jorge-miarnau
* Copisa: Josep Cornadó Mateu > http://quienmanda.es/people/josep-cornado-mateu
* Sando: José Luis Sánchez Domínguez > http://quienmanda.es/people/jose-luis-sanchez-dominguez

**Comment by rauldiazpoblete** [comment]
He añadido en https://github.com/civio/quiencobralaobra/commit/77c85fe8dd4db5c69e7f95a6ea990cdf90dde6d5 los estilos y he metido el listado de fotos en el artículo.
Aún nos falta conseguir las fotos de los señores de Aldesa y Sanjose y ver si maqueamos las fotos con un casco

**Comment by rauldiazpoblete** [comment]
Hay que modificar también el listado de ids de QM para quitar SANJOSE y Aldesa y meter Copisa y Sando

**Comment by rauldiazpoblete** [comment]
El listado de ids de QM está actualizado en https://github.com/civio/quiencobralaobra/commit/8e1cf45a8dc1fab39359a961f249b95b08eb6e58 y los señores de Copisa y Sando añadidos. 
Ya sólo falta meter los casquitos a las fotos.
