### ISSUE TITLE
Definir la id de QM en los mayores grupos constructores para añadir si grafo de QM

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#79]

**Comment by rauldiazpoblete** [comment]
Mi primera intención ha sido añadir una propiedad `qm_id` en `Bidders` para definir desde el admin la id de QM de los mayores grupos. Pero me he dado cuenta de que en realidad no tenemos ninguna entidad _Grupo_ sino varias entidades _Empresa_ que comparten la propiedad `group`, así que no veo la manera de hacerlo desde el admin.
La única alternativa que se me ocurre es añadir un hash de ids de QM a pelo en el controller de `Bidders` y recoger la id a partir del nombre de cada grupo.

**Comment by rauldiazpoblete** [comment]
He añadido en https://github.com/civio/quiencobralaobra/commit/22b0f1e7a104324234abdc083726d042850f57d0 un hash en `BiddersController` que mapea los _slugs_ de los _"Reyes del ladrillos"_ (ACS, Acciona, Isolux, Ferrovial, FCC, Sacyr, Villar Mir, Aldesa, San José y Comsa) con sus ids de QM. En aquellos Grupos con id de QM mostramos su gráfico justo delante de la tabla de contratos (si lo ponemos detrás no lo verá nadie).
La solución es un poco chusca pero no se me ocurría nada mejor. Cierro el issue y en caso de que encontremos un mejor método lo volvemos a reabrir.

**Comment by dcabo** [comment]
Me parece bien para salir del paso. 👍
