### ISSUE TITLE
UTE con salto de línea final en tabla 'bidders'

### ISSUE THREAD

**Issue by esebastian** [civio/quiencobralaobra#81]
La UTE 'UTE: Puebla y Estéllez S.A. / Técnicas Ambientales del Oeste S.L.' se ha importado en la tabla `bidders` con un salto de línea final, mientras que en la tabla `ute_companies_mappings` no lo tiene

**Comment by esebastian** [comment]
He hecho un update en la tabla `bidders` para eliminar el salto de línea, faltaría ver si hace falta corregirlo en el Excel a partir del cual se ha generado el CSV desde donde se han importado los datos.

**Comment by dcabo** [comment]
He arreglado el Excel del año en cuestión y he regenerado el CSV maestro (2009-2015), que está subiéndose a Box (y también hay una copia en [Dropbox](https://dl.dropboxusercontent.com/u/531246/2009-2015.csv)). Gracias, Eduardo.

No hace falta volver a cargar los datos porque Eduardo lo arregló directamente en la bbdd, así que cierro el issue.
