### ISSUE TITLE
Revisar la query de data/administraciones

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#82]

**Comment by rauldiazpoblete** [comment]
En `/data/administraciones` aparecen administraciones como `Otros Poderes Adjudicadores`, `Administración Local` o `Universidades` que en realidad no son administraciones en sí, sino tipos de administraciones.
Deberíamos modificar la query para eliminar estas entradas. @dcabo,  ¿se te ocurre a qué puede deberse que aparezcan estos casos?

**Comment by dcabo** [comment]
Raúl, ¿cómo usas tú los resultados de estas queries? En realidad están haciendo bastante más de lo que deberían, mirando importes y procedimientos y cosas así, cuando tú sólo quieres una lista de grupos y otra de administraciones públicas, no?

¿Empresas o grupos, por cierto?

Bastaría con cambiar las queries por algo tipo `select distinct group from bidders` o `select distinct name from public_bodies`.

**Comment by dcabo** [comment]
Cuando pregunto cómo lo usas me refiero a dos cosas, en realidad:

* ¿Qué campos esperas que haya?
* ¿Dónde usas esto? ¿En los desplegables del formulario? Si es así, ¿lo quieres ordenado por importe o alfabéticamente?

**Comment by rauldiazpoblete** [comment]
En realidad esta query es el equivalente de administraciones de la mega-query de los reyes del ladrillo: la necesito para el gráfico de la página de administraciones con las 10 mayores administraciones por importe adjudicado. En la query actual se devuelven todas las administraciones y yo las ordeno por importe y trunco las 10 primeras desde javascript pero lo ideal sería hacerlo en la propia query (a ser posible).
En cuanto a los campos que necesito son los que hay ahora: `administración`, `procedimiento` e `importe` (no necesito el número de contratos) y habría que añadirle el `slug` de la administración.

**Comment by dcabo** [comment]
Lo dejo en manos de eduardo. Es una query mas sencilla, porque no entran en juego utes ni historias. Eduardo, la query actual mira el procedimiento y la tramitacion en las properties, pero ahora lo tenemos todo limpio en el objeto award: process_track y process_type

/david

David Cabo
@dcabo
Director, Fundación Ciudadana Civio
www.civio.es

**Comment by dcabo** [comment]
Claro, el formulario se rellena con lo que le pasa el controller directamente, no es un rollo ajax. No sé en que estaba pensando.

/david

David Cabo
@dcabo
Director, Fundación Ciudadana Civio
www.civio.es

**Comment by EvaBelmonte** [comment]
@esebastian ¿te encargas tú de esto?

**Comment by esebastian** [comment]
En principio estaría resuelto en eae33c7, pero como la lista ha cambiado dejo la issue abierta hasta que hayamos verificado los números.

**Comment by dcabo** [comment]
@esebastian: en la nueva query hay que quitar lo de `WHERE properties -> 'Análisis - Tipo' = 'Obras'`, es una reliquia de hace meses, de cuando usé esta query para hacer cálculos internos.

@rauldiazpoblete, @EvaBelmonte: en este gráfico entiendo que queréis mostrar el importe total de cada administración, desglosado por procedimiento. Si el procedimiento no se conoce lo mostramos como una categoría 'desconocido' en el gráfico, no? Si lo estoy entendiendo correctamente habría que quitar entonces también la parte de `process_type <> ''` de la query, @esebastian.

@rauldiazpoblete, ¿la query de `data/empresas` se está usando? Porque esa también tiene problemas similares: se hizo hace meses para uso interno y no está usando las versiones limpias de los campos. Aunque sospecho que no se usa y que ha sido reemplazada por `data/grupos_constructores`.

**Comment by EvaBelmonte** [comment]
Sí, desglosado por procedimiento. Lo que pasa es que en principio el plan era tenerlo en tres categorías: abierto/negociado/otros. Pero igual es muy apurado juntar tipos de procedimiento en esos bloques, así que para salir tenemos tres opciones (a decisión de @rauldiazpoblete, dependiendo de lo que cueste y de si da tiempo, que no lo sé):

- Agrupar en abierto/negociado/otros (más apagado, tipo gris). La mejor opción, pero no sé si la más factible.
- Meter todos los tipos de procedimiento que tenemos ahora mismo sin agrupar (ahí entiendo que es un cacao de colores y es una pena que los tres negociados no vayan juntos).
- Salir con la barra de un solo color por el momento y arreglarlo una vez hayamos lanzado.

**Comment by rauldiazpoblete** [comment]
Yo puedo agrupar los procedimientos vía javascript en abierto/negociado/otros de cara al gráfico.
@eduardo, ¿te encargas tú de corregir los 2 detalles que comenta David de la query?
@dcabo efectivamente la query de `data/empresas` ya no la usamos, así que me encargo yo de eliminarla

**Comment by esebastian** [comment]
Si al final resulta preferible agrupar los tipos de contrato en el back, avisadme y le pego un vistazo.

**Comment by rauldiazpoblete** [comment]
Ya he agrupado yo los tipos de procedimiento via javascript en https://github.com/civio/quiencobralaobra/commit/ac016c1b93938e486dac879dd51076272cf90f77 y corregido las 2 cositas que comentaba David en la query en https://github.com/civio/quiencobralaobra/commit/84981c9f9b083fef492c0d7f49a27983bde9cfb9, así que podemos dar por cerrado este issue.
