### ISSUE TITLE
UTE que no aparece partida en la web

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quiencobralaobra#83]
Miguel ha encontrado esta empresa, que en realidad es una UTE sin partir: http://mola.quiencobralaobra.es/grupos-constructores/dragados-iza-obras-y-promociones

La he buscado en los archivos de @dcabo de 'Mapeo nombres UTE' y sí que aparece como UTE y partida en dos: Dragados + Iza Obras y promociones. ¿Qué ha podido pasar para que no se muestre partida en la web? 

Ojo: necesito saber si el fallo es en la carga a la web o anterior, porque si los datos con los que yo he trabajado están mal, tanto las cifras del porcentaje que son UTE como las cifras de Dragados (ACS).

**Comment by EvaBelmonte** [comment]
Asigno a porrón porque no sé quién lo puede mirar mejor. Sorry ;)

**Comment by esebastian** [comment]
En realidad pasa con todas las UTEs cuyos componentes no pertenecen todos al mismo grupo, porque en ese caso el valor de la columna `group` no es el nombre de un grupo sino el propio nombre de la UTE.

Le pego un vistazo para ver como evitarlo.

**Comment by EvaBelmonte** [comment]
Es importante que tengamos en cuenta que ese tipo de UTE (con todos los miembros del mismo grupo) se suman a las tablas "en solitario" y no a las de "en UTE".

**Comment by rauldiazpoblete** [comment]
En realidad esto es así porque no se ha realizado el issue #58. Mientras no realicemos este issue y podamos partir el nombre de la UTE en los grupos que lo conforman y linkar a cada grupo seguiremos teniendo este problema. Mi duda es si seremos capaces de completar #58 antes de salir o deberíamos buscar una alternativa

**Comment by EvaBelmonte** [comment]
Lo dejamos en el #58. Cierro aquí. Gracias por las explicaciones
