### ISSUE TITLE
Asignar como 'en solitario' las cantidades de UTE que sí tienen el porcentaje incorporado

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quiencobralaobra#84]
[Para más adelante, no lanzamiento]

Hay algunas UTE que, ya en su nombre, ponen qué porcentaje tiene cada empresa. Son pocos casos pero, dado que sí tienen esa información, podríamos tratarlas como cuando sumamos a los contratos en 'solitario' UTE en las que todas las empresas son del mismo grupo, pero en este caso aplicando los porcentajes. 

Sería:
- [ ] Calcular los % sobre el importe de adjudicación y añadirlo a la suma de 'en solitario'.
- [ ] Recalcular porcentajes y cifras que varíen por esos cálculos.
- [ ] Explicarlo en la metodología, cuando hablamos de UTE, y en el artículo sobre la opacidad de las UTE. 

En todo caso, podemos hacerlo más adelante y, siendo realistas, cuando añadamos un año nuevo -2016- y abramos de nuevo el melón.

**Comment by dcabo** [comment]
Voy a cerrar esto porque cuatro años después el tema UTEs ha cambiado con la nueva ley, así que el puzzle este que imaginábamos en su día no tiene mucho sentido.
