### ISSUE TITLE
Añadir articulo del teaser en Articulos

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#86]

**Comment by rauldiazpoblete** [comment]
Hay que añadir el del 60% de ....

**Comment by EvaBelmonte** [comment]
Ojo que lleva gráfico dentro. Si ves que queda muy mal, lo puedo sacar. O tocarle los colores.

**Comment by rauldiazpoblete** [comment]
Añadido en http://quiencobralaobra.es/articulos/el-60-por-ciento-de-los-contratos-de-los-ministerios-en-2014-se-adjudicaron-sin-concurso.
@EvaBelmonte este artículo no lleva entradilla, por si quieres añadirle tú una. Y el gráfico queda bien.
