### ISSUE TITLE
Los embebidos de QM no funcionan al activar https

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quiencobralaobra#92]

**Comment by rauldiazpoblete** [comment]
Hay un error al intentar cargar el iframe de QM, por ejmplo en https://quiencobralaobra.es/grupos-constructores/acs

**Comment by dcabo** [comment]
El problema es que estamos intentando embeber un iframe vía HTTP cuando QCLO está siendo servida vía HTTPS. El navegador lo bloquea por seguridad ('mixed content').

Ahora mismo no vamos a poder activar HTTPS para QM (he estado un rato intentándolo, siguiendo [estas instucciones](https://medium.com/should-designers-code/how-to-set-up-ssl-with-lets-encrypt-on-heroku-for-free-266c185630db#.6wlmzax75), pero hay que redesplegar QM con un fichero, ahora mismo es un poco lío), así que vamos a desactivar el HTTPS temporalmente. Eduardo, ¿te encargas?

**Comment by esebastian** [comment]
Ok, pero le puedo echar un ojo a lo de Heroku. Otra opción podría ser mover QM a rafael y tenerlo desplegado allí.

**Comment by dcabo** [comment]
Ahora no da tiempo a mover QM, y para mostrar contenido estático en Heroku y que se apruebe el certificado hay que redesplegar QM en Heroku, que es algo que prefiero no hacer ahora porque lleva meses sin actualizarse y seguro que peta algo al intentar redesplegar. La solución buena es moverlo a Rafael, cuando tengamos un momento. Así que vamos a quitar el HTTPS para el lanzamiento, y lo activamos otra vez cuando movamos QM a Rafael.

**Comment by esebastian** [comment]
Ya está desactivado el HTTPS.

**Comment by dcabo** [comment]
Perfecto, gracias Eduardo!

**Comment by EvaBelmonte** [comment]
Reviso enlaces en textos y en los boletines de Javi. En la galería los coge bien
