### ISSUE TITLE
¿Falta la dependencia D3.js en local?

### ISSUE THREAD

**Issue by dcabo** [civio/quiencobralaobra#93]
Raúl, no veo los gráficos en local, es como si no se estuviera incluyendo la librería. Pero en producción funciona, al menos antes de recompilar los assets. ¿Alguna idea de por qué me pasa esto? ¿Tengo que hacer algo en local? ¿Dónde se supone que se incluye D3.js?

**Comment by esebastian** [comment]
@dcabo Raúl ha creado un package.json para instalar las dependencias de módulos de d3 y crear nuestro propio bundle de d3 sólo con los módulos que necesitamos.

Tendrás que hacer un `ppm install` para que funcionen.

**Comment by dcabo** [comment]
Ay, Javascript y sus paquetes. Me da un error, al ejecutar el `rollup`:

````
neko:quiencobralaobra(master) $ rollup -c -o app/assets/javascripts/dist/d3-bundle.js

/usr/local/lib/node_modules/rollup/dist/rollup.js:62
	for ( var item of map.entries() ) {
	               ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/rollup/bin/rollup:5:14)
````

**Comment by dcabo** [comment]
Ok, arreglado, he tenido que actualizar la versión de `node`. Gracias, Eduardo.
