### ISSUE TITLE
¿Estamos mostrando todos los grupos en los listados?

### ISSUE THREAD

**Issue by dcabo** [civio/quiencobralaobra#94]
Tengo que comprobarlo, pero es posible que los que solo han ganado contratos vía UTEs se estén quedando fuera.

**Comment by EvaBelmonte** [comment]
Por si sirve para comprobarlo: 
De los 2.489 grupos empresariales analizados, solo 1.327 se presentaron siempre en solitario. Del resto, 1.162 están en alguna UTE y **641** solo se presentan de esa forma, nunca por sí solos.

**Comment by EvaBelmonte** [comment]
He comprobado tres, y efectivamente no se han creado las páginas de estas empresas y no están en el listado de grupos constructores:

http://quiencobralaobra.es/grupos-constructores/actia-iniciativa-sl
http://quiencobralaobra.es/grupos-constructores/adober-electricidad-sl
http://quiencobralaobra.es/grupos-constructores/agefred-sa

¿Lo podemos solucionar para que esté bien el miércoles?

**Comment by rauldiazpoblete** [comment]
Imagino que es cosa de la query que utilizamos para recoger las empresas, que excluye aquellas que son UTE:

Por ejemplo en `bidders_controller#index`:
`Bidder.select(:group, :slug).distinct.where(<<-EOQ, "#{params[:name]}%").order(slug: :asc)
                 "bidders"."slug" ILIKE ? AND
                 "bidders"."group" NOT IN (
                   SELECT ute
                   FROM ute_companies_mappings
                 )
               EOQ`

**Comment by dcabo** [comment]
Sí, lo arreglo hoy

/david

David Cabo
@dcabo
Director, Fundación Ciudadana Civio
www.civio.es

**Comment by dcabo** [comment]
Eduardo, voy a hacer lo que comentamos de añadir a la tabla de bidders los grupos de las UTEs cuando cargo éstas. ¿Puedes revisar las queries (bueno, la query gorda, básicamente), para ver si estamos dependiendo de alguna manera en que las UTEs no estén ahí? Yo creo que no, pero por si acaso. En cualquier caso, yo verificaré los resultados globales antes de desplegar.

**Comment by esebastian** [comment]
Lo que hacemos en la query ahora es mirar el contenido de la columna `group` de `bidders` y compararla con la columna `ute` de `ute_companies_mapping` para saber si es una UTE o no.

**Comment by dcabo** [comment]
¿Puedes modificar la query para usar la nueva columna `bidders.is_ute`? Así evitamos cambios inesperados cuando yo rellene la tabla con los nuevos grupos.

**Comment by dcabo** [comment]
He modificado el script de carga de datos de UTEs para que cree Bidders si no existen. He vuelto a cargar las UTEs en producción, y ahora ya tenemos el listado completo de grupos tanto en el formulario de filtrado como en el listado de grupos. Por ejemplo, "Adober".

Aún quedan dos cosas por arreglar:

* [ ] El robotexto en los nuevos grupos (como [Adober](http://quiencobralaobra.es/grupos-constructores/adober-electricidad-sl)) es un poco *meh*, vamos a adaptarlo un poco.
* [ ] El listado de contratos está mostrando los contratos en solitario, no vía UTE, así que no aparecen los de estos nuevos grupos.
